version: '3.1'

services:

  postgresql:
    image: postgres
    container_name: container-authenticateuserdb
    environment:
      - POSTGRES_PASSWORD=isaias963
      - POSTGRES_USER=isaiasiotti
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"